apiVersion: v1
kind: Service
metadata:
  name: nginx-service-container2
spec:
  type: NodePort
  selector:
    app: multi-container
  ports:
  - name: container2
    port: 8090
    targetPort: 8090
    nodePort: 30090
