apiVersion: v1
kind: Service
metadata:
  name: nginx-service-container1
spec:
  type: NodePort
  selector:
    app: multi-container
  ports:
  - name: container1
    port: 8080
    targetPort: 8080
    nodePort: 30080
